[info]
full_name = 'd20_spread1_u02_acc_JKR'
short_name = 'D20'

[adhdistrib]
nbins = 2000
fmax = 20.0

dist_params  = 'custom'
medians = [ 0.0079, ]
spreads = [ 6.2592, ]

[sizedistrib]
nbins = 1
width = 3.0

modes   = [ 10.0, ]
spreads = [ 0.0, ]
weights = [ 1.0, ]

[simulation]
duration = 1.0
dt = 1e-3

target_vel = 0.5
acc_time = 0.1

vectorized = true

[physics]
adhesion_model = 'JKR'

density = 1.293
viscosity = 1.52e-5
surface_energy = 0.15

# Parameters of the aerodynamic quantities model
drag_coeff = 1.0

lift_coeff = 1.0
lift_power = 2.31

burst_coeff = 0.0413
