[info]
full_name = 'd20_spread1_u02_acc_JKR'
short_name = 'D20'

[adhdistrib]
nbins = 1000
fmax = 2.0

dist_params  = 'biasi'
medians = [ 1.0, ]
spreads = [ 1.0, ]

[sizedistrib]
nbins = 50
width = 3.0

modes   = [ 10.0, ]
spreads = [ 1.0, ]
weights = [ 1.0, ]

[simulation]
duration = 1.0
dt = 1e-3

target_vel = 0.2
acc_time = 0.1

vectorized = false

[physics]
adhesion_model = 'JKR'

density = 1.293
viscosity = 1.52e-5
surface_energy = 0.15

# Parameters of the aerodynamic quantities model
drag_coeff = 1.0

lift_coeff = 1.0
lift_power = 2.31

burst_coeff = 1.0
