[distribution]
nparts  = 1e9
nbins   = 1000

radii   = [ 10.0, 5.0 ]
rad_spreads = [ 1.0, 0.5 ]

params  = 'biasi'
adh_medians = [ 1.0, 1.0 ]
adh_spreads = [ 1.0, 1.0 ]

[physics]
adhesion_model = 'Rabinovich'
