[adhdistrib]
nparts  = 1e9
nbins   = 1000
fmax = 2.0

params  = 'biasi'
medians = [ 1.0, 1.0 ]
spreads = [ 1.0, 1.0 ]

[sizedistrib]
nbins = 50
width = 3.0

modes   = [ 10.0, 5.0 ]
spreads = [ 1.0, 0.5 ]
weights = [ 2.0, 1.0 ]

[physics]
adhesion_model = 'Rabinovich'
