[info]
full_name = 'example'
short_name = 'example'

[adhdistrib]
nbins = 5000
fmax = 0.5

biasi = true

[sizedistrib]
nbins = 1
width = 3.0

modes   = [ 5.0, ]
spreads = [ 0.0, ]
coeffs = [ 1.0, ]

[simulation]
duration = 10.0
dt = 1e-4

target_vel = 0.6
acc_time = 0.0
transition = 'constant'
perturbation = false

vectorized = false

[physics]
adhesion_model = 'JKR'
resuspension_model = 'RnR'
drag_model = 'oneill'

density = 1.293
viscosity = 1.52e-5
surface_energy = 0.15

# Parameters of the aerodynamic quantities model
drag_coeff = 1.0
lift_coeff = 1.0

burst_coeff = 0.0413
frms = 0.366
