[info]
full_name = 'reeks'
short_name = 'reeks'

[adhdistrib]
nbins   = 5000
fmax = 30.0

dist_params  = 'biasi'
medians = [ 0.01047, ]
spreads = [ 20.0, ]

[sizedistrib]
nbins = 50
width = 3.0

modes   = [ 5.0, ]
spreads = [ 0.0, ]
weights = [ 1.0, ]

[simulation]
duration = 1.0
dt = 0.5

target_vel = 0.9
acc_time = 0.0

vectorized = true

[physics]
adhesion_model = 'JKR'
resuspension_model = 'RnR'

density = 1.181
viscosity = 1.539e-5
surface_energy = 0.56

# Parameters of the aerodynamic quantities model
drag_coeff = 1.0

lift_coeff = 1.0
lift_power = 2.31

burst_coeff = 0.0413

frms = 0.2
