[info]
full_name  = 'reeks10'
short_name = 'reeks10'

[adhdistrib]
nbins = 5000
fmax  = 0.5

biasi = true

[sizedistrib]
nbins = 1
width = 3.0

modes   = [ 5.0, ]
spreads = [ 0.0, ]
coeffs = [ 1.0, ]

[simulation]
read_from_file = false

duration = 1.0
dt = 0.5

target_vel = 0.9
acc_time = 0.0
transition = 'constant'
perturbation = false

vectorized = true

[physics]
adhesion_model     = 'JKR'
resuspension_model = 'RnR'
drag_model         = 'oneill'

density        = 1.181
viscosity      = 1.539e-5
surface_energy = 0.56

# Parameters of the aerodynamic quantities model
drag_coeff = 1.0
lift_coeff = 1.0

burst_coeff = 0.0413
frms = 0.366
