[info]
full_name = 'velocity_from_file'
short_name = 'velocity_from_file'

[adhdistrib]
nbins = 5000
fmax = 0.5

biasi = true

[sizedistrib]
nbins = 1
width = 3.0

modes   = [ 5.0, ]
spreads = [ 0.0, ]
coeffs = [ 1.0, ]

[simulation]
read_from_file = true
input_file = "velocity"

# In this case, this is a new sampling rate
dt = 1e-3

vectorized = false

[physics]
adhesion_model = 'JKR'
resuspension_model = 'RnR'
drag_model = 'oneill'

density = 1.293
viscosity = 1.52e-5
surface_energy = 0.15

# Parameters of the aerodynamic quantities model
drag_coeff = 1.0
lift_coeff = 1.0

burst_coeff = 0.0413
frms = 0.366
