[info]
full_name = 'd10_nospread_u06_acc_JKR'
short_name = 'RnR+perturb'

[adhdistrib]
nbins = 5000
fmax = 20.0

dist_params  = 'biasi'
medians = [ 0.0079, ]
spreads = [ 6.2592, ]

[sizedistrib]
nbins = 1
width = 3.0

modes   = [ 5.0, ]
spreads = [ 0.0, ]
weights = [ 1.0, ]

[simulation]
duration = 10.0
dt = 1e-4

target_vel = 0.5
acc_time = 0.0
transition = 'instant'
perturbation = true

vectorized = false

[physics]
adhesion_model = 'JKR'
resuspension_model = 'RnR'

density = 1.293
viscosity = 1.52e-5
surface_energy = 0.15

# Parameters of the aerodynamic quantities model
drag_coeff = 1.0

lift_coeff = 1.0
lift_power = 2.31

burst_coeff = 0.0413

frms = 0.3